title: "Work with Bola"
description: "Your Digital Fixer & Business Packaging Partner. Websites, branding, documents — I help you package your business so it's taken seriously."
url: "https://workwithbola.xyz"
email: "bolaolaniyanadedayo@gmail.com"
phone: "+2349071953226"
social:
  instagram: "https://www.instagram.com/workwithbola/"
  linkedin: ""
  twitter: ""